<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DisplayRecords.aspx.cs" Inherits="Search.DisplayRecords" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 577px;
        }
       #Button1 {
            position: absolute;
            right: 30px;
            top: 85px;
            margin:auto;
        }
        .auto-style2 {
            right: 20px;
            top: 100px;
            width: 100px;
            height: 29px;
        }
        
    </style>
</head>
<body style="background-color: lightblue;">
    <form id="form1" runat="server">
        <div>
            <center class="auto-style1">
                <h1>Search Records From The Database</h1>
                 
                
                <hr />
            Search: <asp:TextBox ID="Txtsearch" runat="server"></asp:TextBox>
            <asp:Button ID="ButSearch" runat="server" Text="SEARCH" OnClick="ButSearch_Click" />
            <asp:Button ID="Button1" runat="server" Text="Register Here" CssClass="auto-style2" OnClick="Button1_click"   />
               
               
            <hr />
            <asp:GridView ID="GridView1" runat="server" ShowHeaderWhenEmpty="True" EmptyDataText="No Records Found !" CellPadding="4" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />

            </asp:GridView>
                
                <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="id" DataSourceID="SqlDataSource1" GridLines="Vertical">
                    <AlternatingRowStyle BackColor="#DCDCDC" />
                    <Columns>
                        <asp:BoundField DataField="id" HeaderText="id" InsertVisible="False" ReadOnly="True" SortExpression="id" />
                        <asp:BoundField DataField="user_name" HeaderText="user_name" SortExpression="user_name" />
                        <asp:BoundField DataField="email_address" HeaderText="email_address" SortExpression="email_address" />
                        <asp:BoundField DataField="dob" HeaderText="dob" SortExpression="dob" />
                        <asp:BoundField DataField="mobile_number" HeaderText="mobile_number" SortExpression="mobile_number" />
                        <asp:BoundField DataField="state" HeaderText="state" SortExpression="state" />
                        <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                    <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#0000A9" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#000065" />
                </asp:GridView>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:ConString %>" DeleteCommand="DELETE FROM [register] WHERE [id] = @id" InsertCommand="INSERT INTO [register] ([user_name], [email_address], [dob], [mobile_number], [state], [city]) VALUES (@user_name, @email_address, @dob, @mobile_number, @state, @city)" SelectCommand="SELECT * FROM [register]" UpdateCommand="UPDATE [register] SET [user_name] = @user_name, [email_address] = @email_address, [dob] = @dob, [mobile_number] = @mobile_number, [state] = @state, [city] = @city WHERE [id] = @id">
                    <DeleteParameters>
                        <asp:Parameter Name="id" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="user_name" Type="String" />
                        <asp:Parameter Name="email_address" Type="String" />
                        <asp:Parameter DbType="Date" Name="dob" />
                        <asp:Parameter Name="mobile_number" Type="String" />
                        <asp:Parameter Name="state" Type="String" />
                        <asp:Parameter Name="city" Type="String" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="user_name" Type="String" />
                        <asp:Parameter Name="email_address" Type="String" />
                        <asp:Parameter DbType="Date" Name="dob" />
                        <asp:Parameter Name="mobile_number" Type="String" />
                        <asp:Parameter Name="state" Type="String" />
                        <asp:Parameter Name="city" Type="String" />
                        <asp:Parameter Name="id" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>
                </center>
        </div>
    </form>
</body>
</html>